### ISSUE TITLE
Scheduler priority problem with temp files

### ISSUE THREAD

**Issue by gaetansnl** [snakemake/snakemake#1031]
**Snakemake version**
6.3.0

**Describe the bug**

In my workflow, for each sample, I have a first step that creates a large temporary file (>1GB). Subsequent steps are depending on this first step. I use the ilp scheduler which " remove temporary files as fast as possible". The problem is that in my workflow it does the opposite, that is filling the disk  with temporary files and not doing steps to remove it.

It's a big problem for us because we do 2000 samples at once and there is no way we can get such large disks to store all the temporary files

I reproduced a small example

**Minimal example**

All examples use `snakemake --cores 2`

**WORKING**
The two first final files are created first, and it allows to remove the r1 files

```yaml
DATA = list(str(i) for i in range(4))

rule all:
    input:
        expand("final_{data}", data=DATA),

rule r1:
    output:
        temp("r1_{data}")
    shell:
        """
        dd if=/dev/zero of={output} bs=512 count=1000 oflag=dsync
        sleep 5
        """

rule r2:
    input: "r1_{data}"
    output: "r2_{data}"
    shell:
        """
        touch {output}
        """

rule final:
    input: 
        "r2_{data}",
    output: "final_{data}"
    shell:
        """
        touch {output}
        """
```

**NOT WORKING**

It start r1 again before first two are finished

```yaml
DATA = list(str(i) for i in range(4))

rule all:
    input:
        expand("final_{data}", data=DATA),

rule r1:
    output:
        temp("r1_{data}")
    shell:
        """
        dd if=/dev/zero of={output} bs=512 count=1000 oflag=dsync
        sleep 5
        """

rule r2:
    input: "r1_{data}"
    output: "r2_{data}"
    shell:
        """
        touch {output}
        """
rule r4:
    input: "r2_{data}"
    output: "r4_{data}"
    shell:
        """
        touch {output}
        """

rule final:
    input: 
        "r4_{data}",
    output: "final_{data}"
    shell:
        """
        touch {output}
        """
```
**WORKING** 
When I add fake dependencies on preceding input manually

```yaml
DATA = list(str(i) for i in range(4))

rule all:
    input:
        expand("final_{data}", data=DATA),

rule r1:
    output:
        temp("r1_{data}")
    shell:
        """
        dd if=/dev/zero of={output} bs=512 count=1000 oflag=dsync
        sleep 5
        """

rule r2:
    input: "r1_{data}"
    output: "r2_{data}"
    shell:
        """
        touch {output}
        """
rule r4:
    input: 
        "r2_{data}",
        "r1_{data}"
    output: "r4_{data}"
    shell:
        """
        touch {output}
        """

rule final:
    input: 
        "r4_{data}",
        "r1_{data}"
    output: "final_{data}"
    shell:
        """
        touch {output}
        """
```

**Additional context**
The trick I use to solve the problem is working here because the workflow is simple, but in reality it's very complex to create these fake dependencies....

Maybe it would solve the problem to make the scheduler believe that a step depends on a file if it depends on a step that depends on this file.
