### ISSUE TITLE
AmbiguousRuleException when there is no ambiguity

### ISSUE THREAD

**Issue by dkuzminov** [snakemake/snakemake#1106]
**Snakemake version**
6.5.3

**Describe the bug**
Snakemake may throw an AmbiguousRuleException when there is no ambiguity. This bug depends on the processing order of rules.

**Minimal example**
To reproduce the bug the file *non_existing_file.txt* shall not be present while the file *optional_input.txt* must exist.
```python
rule all:
    input: "target.txt"

rule from_non_existing_file:
    input: "non_existing_file.txt"
    output: "target.txt"

rule broad_input:
    output: "target.txt"

rule narrow_input:
    input: "optional_input.txt"
    output: "target.txt"

ruleorder: narrow_input > broad_input
```
If this script is being run in the `--dry-run` mode multiple times, most of the times it would correctly resolve the ambiguities:
```
Job counts:
        count   jobs
        1       all
        1       narrow_input
        2
```
In 1/6 runs however it would throw an exception:
```
AmbiguousRuleException:
Rules narrow_input and broad_input are ambiguous for the file target.txt.
Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
Wildcards:
        narrow_input:
        broad_input:
Expected input files:
        narrow_input: optional_input.txt
        broad_input: Expected output files:
        narrow_input: target.txt
        broad_input: target.txt
```

**Additional context**
In the example above there are 3 rules that claim *target.txt* as their output. One rule (`from_non_existing_file`) should be eliminated because of missing input. For the other two there is an explicit `ruleorder` defined, and the `narrow_input` shall be preferred if the file *optional_input.txt* exists. However this behaviour is not stable and in approx. 1/6 runs Snakemake forgets of the explicit `ruleorder` defined.
