### ISSUE TITLE
Schema validation doesn't seem to work for deep config.yaml levels

### ISSUE THREAD

**Issue by seb-mueller** [snakemake/snakemake#1390]
**Snakemake version**

6.15.5

**Describe the bug**

Following [the validation manual](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html?highlight=schema#validation), I've tried to get `config.yaml` validated.
This worked fine until a reached a certain depth of nesting.

**Logs**

**Minimal example**

I've placed the 3 below files in the same directory:
**config.yaml**
```
level1:
  level2-string: text2
  level2:
    level3-string: 3
    level3:
      level4-string: 4
```
**config.schema.yaml**
```
$schema: "http://json-schema.org/draft-07/schema#"

properties:
  level1:
    type: object
    properties:
      level2-string:
        type: string
      level2:
        type: object
        properties:
          level3-string:
            type: string
          level3:
            level4-string:
              type: string
```
**Snakefile**
```
from snakemake.utils import min_version, validate
configfile: "config.yaml"
validate(config,  schema=os.path.join("config.schema.yaml"))

rule all:
    input:
        expand("test.{sample}.txt", sample="a")

rule a:
    output:
        "test.{sample}.txt"
    shell:
        "touch {output}"
```

When running `snakemake --cores 1`, I correctly get a failed scheme validation, since `level3-string` is supposed to be a `string` but an integer is provided.

```
WorkflowError in line 3 of Snakefile:
Error validating config file.
ValidationError: 3 is not of type 'string'

Failed validating 'type' in schema['properties']['level1']['properties']['level2']['properties']['level3-string']:
    OrderedDict([('type', 'string')])

On instance['level1']['level2']['level3-string']:
    3
  File "Snakefile", line 3, in <module>
```

So all is fine so far, but if `config.yaml` is changed to this (3 -> text3): 

**config.yaml**
```
level1:
  level2-string: text2
  level2:
    level3-string: text3
    level3:
      level4-string: 4
```
I would expect the validation to fail at `level4-string` , but snakemake completes to job succesfully, even though it shouldn't since `level4-string` should fail since it is supposed to be a `string`!

**Comment by seb-mueller** [comment]
Just an update, this bug is still persistence in `7.18.2` and quite severe in my opinion since it basically make scheme validation unusable.

**Comment by pvandyken** [comment]
Looks like you have a mistake in your schema

```
$schema: "http://json-schema.org/draft-07/schema#"

properties:
  level1:
    type: object
    properties:
      level2-string:
        type: string
      level2:
        type: object
        properties:
          level3-string:
            type: string
          level3:
            type: object
            properties:
              level4-string:
                type: string
```

Note the extra content under `level3`. Does the above work as expected?
