### ISSUE TITLE
use `srun` with `script:` instead of `shell:`

### ISSUE THREAD

**Issue by berceanu** [snakemake/snakemake#1394]
One of my rules involves a SLURM job that needs to be ran via MPI over several GPUs. Based on the original SLURM script, I came up with:

```yaml
rule compute_spectrum:
    input:
        "results/h5/tracks.h5"
    output:
        "results/h5/spectrum.h5"
    conda:
        "envs/synchrad.yaml"
    resources:
        ntasks=config["ngpus"],
        ngpus=config["ngpus"],
    benchmark:
        f"benchmarks/compute_spectrum/{config['ngpus']}.tsv"
    shell:
        "srun -n{resources.ngpus} --mpi=pmi2 python scripts/compute_spectrum.py -i {input} -o {output}"
```

While this works, since what I am running is a Python script and not really a shell command, I would like to be able to somehow use `script:` instead of `shell:` so that I can access the `snakemake` object from `compute_spectrum.py` and not resort to `argparse` and co.
