### ISSUE TITLE
version gathering of used softwares

### ISSUE THREAD

**Issue by Smeds** [snakemake/snakemake#1598]
We are developing pipelines that are used in clinical settings and one feature that we are missing right now is a easy way of gathering all version of softwares that have been used, for example which version of bwa was used in the conda/singularity environment. Our pipeline are version tracked and one could easilly save version of pipeline to a file, but then you would have to go into the code to find out which version have been run. What we would like is an option of printing version of each software to a json-file, each time the pipeline is run.

**Describe the solution you'd like**
It would be neat if you could specify in the rule how to extract which softwares have been used' 

```
rule bwa_align:
    input: ....
    output: ...
    version_command:
       "bwa": "bwa 2>&1  | awk '{if(/Version/) print($2)}'",
       "samtools": "samtools 2>&1  | awk '{if(/Version/) print($2)}'"
    version_file:
       "bwa_align.json"
    wrapper:
        "v1.3.1/bio/bwa/mem"
```

which would maybe generate the following file:
```
{
   "bwa_align": {
        "bwa": "0.7.12-r1039",
        "samtools": "1.10"
    }
}
```
