### ISSUE TITLE
Mismatch of python/pandas/numpy versions leads to error under very specific circumstances

### ISSUE THREAD

**Issue by lczech** [snakemake/snakemake#1640]
**Snakemake version**
Tested with 7.6.1 (latest) and 5.32.1

**Describe the bug**
This is an incredibly weird bug that only occurs under very (!) specific circumstances. Unfortunately, exactly those that I currently have in my production code... It took me a while to distill this down to a truly minimal example. [Download the example here](https://github.com/snakemake/snakemake/files/8638665/minimal.zip), and let's walk through it:

First, we want to run snakemake in a conda environment:
```yaml
# env-parent.yaml
name: snakemake-7.6.1
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake=7.6.1
  - python ==3.7.10
  - pandas=1.3.1
  - numpy=1.21.0
```

Use this environement:
```sh
mamba env create -f env-parent.yaml
conda activate snakemake-7.6.1
```

We also have an environment specifically for a rule:
```yaml
# env-rule.yaml
channels:
  - bioconda
  - conda-forge
dependencies:
  # This is where the version mismatch is happening.
  # With 3.10, we get the error, with 3.7.10 not,
  # as that is also what's used in the parent environment.
  - python ==3.10
```

With that, we can then run the following:
```smk
# Snakefile
import pandas as pd

# We need to load a config (does not need to contain anything interesting),
# and then need to add a key to it via pandas.
# The table does not need to contain much, just enough to not fail reading.
# We do not even need to use this config anywhere downstream.
configfile: "config.yaml"
config["table"] = pd.read_csv("table.tsv", sep='\t', dtype=str)

# We need to use a rule-specific conda environemnt, and we need to use a script.
rule all:
    output:
        "dummy.txt"
    conda:
        "env-rule.yaml"
    script:
        # The script just touches the output file.
        "script.py"
```

via
```bash
snakemake --use-conda --cores 1 --conda-frontend mamba
# mamba or conda frontend does not matter
```

This leads to the following error:
```
ImportError: Unable to import required dependencies:
numpy: 
```
<details>
    <summary>Full error message</summary>

    File "/home/lucas/Software/miniconda/envs/snakemake-7.6.1/lib/python3.7/site-packages/pandas/__init__.py", line 16, in <module>
        raise ImportError(
    ImportError: Unable to import required dependencies:
    numpy: 

    IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

    Importing the numpy C-extensions failed. This error can happen for
    many reasons, often due to issues with your setup or how NumPy was
    installed.

    We have compiled some common reasons and troubleshooting tips at:

        https://numpy.org/devdocs/user/troubleshooting-importerror.html

    Please note and check the following:

      * The Python version is: Python3.10 from "/home/lucas/Downloads/tmp/.snakemake/conda/c8bba9192d80f12dcd954355d2a0791e/bin/python"
      * The NumPy version is: "1.21.0"

    and make sure that they are the versions you expect.
    Please carefully study the documentation linked above for further help.

    Original error was: No module named 'numpy.core._multiarray_umath'
</details>

If _any_ of the parts described as "need" in the Snakefile above are not given (not loading a config file, not adding a key to it via pandas, not using a separate conda environment for the rule, not using a script in the rule), the error does not occur. It also disappears if we match the python versions in the two environments. 

I originally discovered the bug because of a rule-specific conda environment that simply loaded a tool instead of python itself, but the tool then pulled the conflicting python version into the environment. That has [originally led me to discover this bug](https://stackoverflow.com/q/72109298/4184258). As a side note - if anyone knows a solution to this problem that is easier than specifying the python version explicitly in every rule-specific environment, please let me know!
