### ISSUE TITLE
Standard build

### ISSUE THREAD

**Issue by flying-sheep** [snakemake/snakemake#1681]
**Snakemake version**
7.8.0, main branch

**Describe the bug**
You’re missing a `pyproject.toml` file specifying the build system.
You rely on legacy build conventions (setup.py) instead of this standard.

**Minimal example**
You can just add a `pyproject.toml` containing the following to fix this:

```toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
```

Later you could e.g. migrate away from setuptools or move its configuration from `setup.cfg` to `pyproject.toml`
