### ISSUE TITLE
Clarification on --default-resources input type

### ISSUE THREAD

**Issue by gibsramen** [snakemake/snakemake#1707]
Snakemake version: 7.3.0

The help for `--default-resources` states that arguments should be of the form `NAME=INT` (name=integer).

https://github.com/snakemake/snakemake/blob/cc6c9986271738dfa8394fc45720a4d756af9d0a/snakemake/__init__.py#L1201-L1217

However, to me it seems that Snakemake is perfectly happy taking a string as a resource. I am using the following profile and from what I can tell the fact that I pass `partition=long` works as intended.

```yaml
cluster: "sbatch --nodes={resources.nodes} --time={resources.runtime} --cpus-per-task={resources.cpus} --mem={resources.mem_mb} --output=slurm_out/{rule}.log --partition={resources.partition}"
use-conda: True
jobs: 10
latency-wait: 60
default-resources: [cpus=4, mem_mb=8000, runtime=60, nodes=1, partition=long]
```

Am I misunderstanding this argument structure? If not, I think it would be useful to change the help message to reflect this.

**Comment by pvandyken** [comment]
I'm not sure you can format a yml list like that... Have you tried like this:

```yaml
cluster: "sbatch --nodes={resources.nodes} --time={resources.runtime} --cpus-per-task={resources.cpus} --mem={resources.mem_mb} --output=slurm_out/{rule}.log --partition={resources.partition}"
use-conda: True
jobs: 10
latency-wait: 60
default-resources: 
  - cpus=4
  - mem_mb=8000
  - runtime=60
  - nodes=1
  - partition=long
```
