### ISSUE TITLE
Cluster jobname and log specified for each rule

### ISSUE THREAD

**Issue by 437364** [snakemake/snakemake#2127]
I run snakemake on a PBS cluster, and I have customized the name of the job and stdout log in my profile config file:

```yaml
---
snakefile: Snakefile
cores: 1
keep-going: True
printshellcmds: True
#shadow-prefix: '$SCRATCH'

# cluster
cluster: "qsub -l select={resources.sel}:ncpus={resources.cpus}:mem={resources.memgb}:scratch_local={resources.scratchgb} -l walltime={resources.walltime} \
        -j oe -o logs/{rule}/{wildcards.sample}.log"
default-resources:
 - sel=1
 - cpus=1
 - memgb="2gb"
 - scratchgb="100gb"
 - walltime="24:00:00"
 #- tmpdir='$SCRATCH'
jobname: "{rule}.{wildcards.sample}.{jobid}"
max-jobs-per-second: 1  
jobs: 15
cluster-cancel: "qdel"
group-components:
 - FastQC-trim=3

```
This works fine for individual jobs, but once I add grouping to the mix, the whole thing falls apart, since the {sample} wildcard is not consistently defined for each group. Also in a case where I aggregate multiple inputs (such as multiQC), using the wildcard does not make sense either. Is it possible to specify jobname and -o log in cluster job properties differently for each rule?
Or is there a better way to handle the logging altogether?

snakefile rules:

```python
import os
import pandas as pd

# create a dictionary from input table of samples that contains name + sra id
samples_information = pd.read_csv("resources/id_table.tsv", sep='\t', index_col=False)
sra_id = list(samples_information['Run'])
sample_id = list(samples_information['sample'])
sample_type = list(samples_information['LibraryLayout'])
samples_dict = dict(zip(sample_id, zip(sra_id, sample_type)))
paired_dict = {key: value for key, value in samples_dict.items() if value == (value[0], 'PAIRED')}
names = [s + "_1" for s in samples_dict.keys()] + [s + "_2" for s in paired_dict.keys()]


rule all:
	input:
		"results/MultiQC/Trim_multiqc_report.html"	
		
rule trimming:
	input:
		fq = "results/raw/{sample}_1.fastq"
	output:
		out = "results/trimmed/{sample}_1_trim.fastq",
	resources:
		memgb="10gb",
		walltime="48:00:00",
		cpus=1
	shell:
		"""
		module add mambaforge-22.9.0
		cd /storage/brno1-cerit/home/kratka/database_holocentrics_workflow/
		mamba activate /storage/brno2/home/kratka/.conda/envs/snakemake
		export OMP_NUM_THREADS=$PBS_NUM_PPN
		trimmomatic SE -phred33 -threads $PBS_NUM_PPN {input.fq} {output.out} \
			ILLUMINACLIP:config/adapters.fa:2:30:10 SLIDINGWINDOW:4:10 MINLEN:60
		"""
rule fastqc_trim:
	input:
		"results/trimmed/{sample}_1_trim.fastq"
	output:
		qc_html = "results/FastQC_trim/{sample}_1_trim_fastqc.html",
		qc_zip = "results/FastQC_trim/{sample}_1_trim_fastqc.zip"
	#shadow:	"minimal" 
	group: "FastQC-trim"
	resources:
		memgb="10gb",
		walltime="48:00:00",
		cpus=1
	run:
		print(wildcards.sample)
	
		shell("module add fastQC-0.11.5; \
		export OMP_NUM_THREADS=$PBS_NUM_PPN; \
		fastqc -o results/FastQC_trim -f fastq -t $PBS_NUM_PPN results/trimmed/{wildcards.sample}_trim.fastq")
		
rule multiqc_trim:
	input:
		expand("results/FastQC_trim/{sample}_1_trim_fastqc.html", sample=samples_dict.keys())
	output:
		"results/MultiQC/Trim_multiqc_report.html"
	shell:
		"""
		module add python27-modules-gcc 
		multiqc -o results/MultiQC -i Trim results/FastQC_trim 
		"""
```
