### ISSUE TITLE
No way to set Julia packages

### ISSUE THREAD

**Issue by MilesCranmer** [snakemake/snakemake#2215]
The Julia interface has no way of allowing a custom `Project.toml`: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#julia. Because `conda` does not host Julia packages, it is unclear how you actually use the Julia interface with packages.

One thing I tried is to set up the `Project.toml`, and have an initial rule be:

```yaml
rule julia_manifest:
    input: "Project.toml"
    output: "Manifest.toml"
    shell: "julia -e 'using Pkg; Pkg.instantiate()'"
```

and then have every rule after it depend on `Manifest.toml` as an input. I also defined the `JULIA_PROJECT` variable as so:

```python
os.environ["JULIA_PROJECT"] = os.getcwd()
```

However, this project setting does not seem to propagate to the internal `julia` scripts:

```yaml
rule data:
    input: "Manifest.toml"
    script: "data.jl"
```

This `data.jl` does not seem to activate in the correct environment.
