### ISSUE TITLE
params do not parse wildcards when the string is the result of a function. 

### ISSUE THREAD

**Issue by y9c** [snakemake/snakemake#2307]
```yaml
rule a    
    params:
        prefix="somedir/{sample}"
```

works, but not 

```yaml
tempdir = Path(".tmp")
rule a:
    params:
        prefix=tempdir / "somedir/{sample}"
```
