### ISSUE TITLE
[BUG] Snakemake fails to detect the correct path of config.yaml file when `executor` plugin is used. 

### ISSUE THREAD

**Issue by y9c** [snakemake/snakemake#2572]
Python version: 3.12
Snakemake version: 8.0.1

When run snakemake starts with `--executor slurm` setting and [snakemake-executor-plugin-slurm](https://github.com/snakemake/snakemake-executor-plugin-slurm) is installed, the following error occurs for each job. However, when snakemake runs using the local executor, there are no errors. 

```
WorkflowError:
Workflow defines configfile config.yaml but it is not present or accessible
```

---

Minimal file to reproduce this bug:

Snakefile

```yaml
configfile: "config.yaml"
workdir: "test"

rule all:
    input: "test.txt"

rule test1:
    output: "test.txt"
    shell: "hostname > {output}
```

config.yaml

```yaml
value1: 1
```
