### ISSUE TITLE
Adressing rules that have been named via the `name` attribute

### ISSUE THREAD

**Issue by richardstoeckl** [snakemake/snakemake#2578]
When creating a rule with a name like this:

```
rule NAME:
    input: 
        inputFile="path/to/inputfile", 
    output: 
        outputFile="path/to/outputfile",
    shell: "somecommand {input.inputFile} {output.outputFile}"
```

the output of the rule can be referenced in a later rule like this, which is uesefull for rule dependencies:

```
rule LATER:
    input: 
        inputFile=rules.NAME.output.outputFile,
    output: 
        outputFile="path/to/other/outputfile",
    shell: "someOTHERcommand {input.inputFile} {output.outputFile}"
```

However, when the Name of the rule is set via the `name` attribute (see [the tutorial](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#snakefiles-and-rules)) this does not seem possible:

```
rule all:
    input:
        expand("output/output{tool}_downstream.txt", tool=["A", "B"])

for tool in ["A", "B"]:
    rule:
        name: f"call_variants_{tool}"
        input: f"input/input{tool}.txt"
        output: f"output/output{tool}.txt"
        shell: f"cat {{input}} > {{output}}"

    rule:
        name: f"downstream_{tool}"
        input: rules.call_variants_{tool}.output,
        output: f"output/output{tool}_downstream.txt"
        shell: f"cat {{input}} > {{output}}"
```

```bash
SyntaxError in file Snakefile, line 14:
invalid syntax
```

I don't find any mention of the correct way of addressing rules named like this within the documentation. Could you please clarify how such a case should be handled? Using `expand("output/output{tool}.txt"),` seems to work, however this does not seem elegant or intended like the `rules.NAME.output` way.

Thank you so much for any help!

Edit: running snakemake version 8.1.0
