### ISSUE TITLE
schema validation doesn't work for arrays in tabular configuration files

### ISSUE THREAD

**Issue by J-Wall** [snakemake/snakemake#2601]
**Snakemake version**
8.1.0

**Describe the bug**
If a field in a schema for a tabular configuration file is type `array`, then `snakemake.utils.validate` fails with `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Minimal example**
samples.tsv:
```tsv
sample	metadata
sample1	["foo","bar"]
```
samples.schema.yaml:
```yaml
$schema: "https://json-schema.org/draft/2020-12/schema"

title: Minimal example showing validation error on array fields
type: object
properties:
  sample:
    type: string
  metadata:
    type: array
    items:
      type: string
required:
 - sample
 - metadata
```
Snakefile:
```python
import pandas as pd
import json
from snakemake.utils import validate

samples = pd.read_table("samples.tsv", converters={"metadata": json.loads}).set_index("samples", drop=False)
validate(samples, "samples.schema.yaml")  # ValueError
```

**Additional context**
The problem is `utils.validate` uses `if not pd.isnull(v)` without any type checking on `v` first. If `v` is array-like (i.e. a list), then `pd.isnull(v)` performs the check element-wise, when actually what is required is a check if the value `v` is itself `NaN`

My suggestion is to change the call to `pd.isnull(v)` to something like this, which returns true if `v` is itself an array or list:
```python
v is not None and not (isinstance(v, float) and pd.isnull(v))
# ^ missing data       ^ only call `pd.isnull(v)` if `v` is a float
# | could be
# | represented as `None`
```
