### ISSUE TITLE
A tree_expand function that constrains format string combinations to stem-to-leaf YAML paths

### ISSUE THREAD

**Issue by bskubi** [snakemake/snakemake#2644]
**Is your feature request related to a problem? Please describe.**
In my pipeline, I define a set of distinct experimental conditions, each with an individual number of biological replicates, and each biological replicate in turn with an individual number of technical replicates.

**Describe the solution you'd like**
This is defined in config.yaml like so:

```
conditions:
  cond1:
    bioreps:
      br1:
        techreps:
          - tr1
          - tr2
      br2:
        techreps:
          - tr2
  cond2:
    bioreps:
       br1:
          techreps:
            - tr1
```

I want to be able to format a template string to have just the combinations of conditions, bioreps, and techreps expressed in this YAML, like so:

tree_expand("{conditions}/{bioreps}/{techreps}.{ext}", config, ['conditions', 'bioreps', 'techreps', ext='.txt')

With output:

`["cond1/br1/tr1.txt", "cond1/br1/tr2.txt", "cond1/br2/tr2.txt", "cond2/br1/tr1.txt"]`

tree_expand should be able to accommodate discrepancies between wildcards in the template string and keys in the YAML.

**Proposed implementation**

I already implemented this for my pipeline, which you can see in the attached tree_expand.py.txt. I would be happy if Snakemake absorbed my code so that it can benefit from community attention. Note that in my version, I actually re-implement the expand() function to permit unit testing outside a snakemake context, but that could of course be replaced by the existing expand function.
