### ISSUE TITLE
Not clear how to set non-standard cluster resource settings with Profiles

### ISSUE THREAD

**Issue by skudashev** [snakemake/snakemake#2682]
Hello, I used to run snakemake on the UGE cluster using --drmaa " V -cwd -l gpu=1 -pe mt {threads}"', in the new versions this option is deprecated, so I installed a [uge profile](https://github.com/meyer-lab-cshl/snakemake-uge). I found that I should create my own uge.yaml which would look something like this:
`__default__:
  - "-P development"
  - "-V"
  - "-cwd"
  - "-pe mt {threads}"

dorado:
  - "l gpu=1"
`
However I am not sure how to add it to the snakemake command? 
snakemake --jobs 50 --latency-wait 30 --use-conda --profile uge

Could you please advise me on that?

**Comment by gemygk** [comment]
@skudashev 
Below is what I use to run snakemake (v8.14.0) on the SLURM cluster

To use snakemake with SLURM we should install [`snakemake-executor-plugin-slurm` ](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html)as part of conda snakemake installation to use `executor: slurm` in the `config.v8+.yaml` below.

### Installation
```console
conda install -y -c bioconda -c conda-forge snakemake=8.14.0 snakemake-executor-plugin-slurm
```

### Example test data
Below is the test directory structure **before** execution

```console
test_run
├── one.txt
├── profiles
│   └── work_profile
│       └── config.v8+.yaml
└── Snakefile
```
where,

[**profiles/work_profile/config.v8+.yaml** ](https://snakemake.readthedocs.io/en/latest/executing/cli.html#profiles)
```yaml
executor: slurm
default-resources:
    # not necessary if not sure about `slurm_account`, snakemake will try to infer this using `sacctmgr`
    slurm_account: "account_name"
    slurm_partition: "queue_name"
    runtime: 2:00:00
    mem_mb: 4096
    slurm_extra: "'--mail-type=END --mail-user=first.last@mail.com -o logs/smk.%N.%j.out -e logs/smk.%N.%j.err'"
printshellcmds: True
jobs: 100
restart-times: 3
latency-wait: 60
rerun-incomplete: True
use-conda: false
set-threads:
    rule1: 1
    rule2: 2
    # rule specific threads
    test: 4
set-resources:
    # rule specific resources
    test:
        slurm_partition: "queue_name"
        runtime: 4:00:00
        mem_mb: 4096
```
**Snakemake**
```yaml
rule all:
    input:
        "done.txt"

rule test:
    input:
        "one.txt"
    output:
        "done.txt"
    log:
        "test.log"
    shell:
        """
        echo "Processing data with {threads} threads" > {log}
        cp {input} {output}
        /usr/bin/time -v sleep 10
        echo "Processing complete" >> {log}
        """
```
**one.txt**
```
empty file
```


### Command
Now we can execute snakemake on SLURM using the `profiles/work_profile`
```console
$ cd test_run
$ snakemake --profile profiles/work_profile  --snakefile Snakefile
Building DAG of jobs...
SLURM run ID: 952ada6a-70b3-44b8-b6d9-30c2ee2fc421
Using shell: /usr/bin/bash
Provided remote nodes: 100
Job stats:
job      count
-----  -------
all          1
test         1
total        2

Select jobs to execute...
Execute 1 jobs...
...
...
Finished job 0.
2 of 2 steps (100%) done
Complete log: .snakemake/log/2024-06-28T103831.904550.snakemake.log
```

Below is the test directory structure **after** execution

```console
test_run
├── one.txt
├── profiles
│   └── work_profile
│       └── config.v8+.yaml
├── Snakefile
├── logs
│   ├── smk.e512n47.1118341.err
│   └── smk.e512n47.1118341.out
├── test.log
└── done.txt
```

### Snakemake and plugin versions
```console
snakemake==8.14.0
snakemake-executor-plugin-slurm==0.7.0
snakemake-executor-plugin-slurm-jobstep==0.2.1
snakemake-interface-common==1.17.2
snakemake-interface-executor-plugins==9.1.1
snakemake-interface-report-plugins==1.0.0
snakemake-interface-storage-plugins==3.2.2
```

### Note
With the current version of snakemake (v8.14.0), the standard SLURM job name is an `UUID` and if you want to see the rule name / wildcard for your jobs with the SLURM `squeue` command, it is now added to the `--comments` section by snakemake

See here
https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/af92fd0430e0b5541094494e29ceb2bc2ac49b97/snakemake_executor_plugin_slurm/__init__.py#L106-L112

and here https://github.com/snakemake/snakemake/issues/2494#issuecomment-2032250329 for details.

We need to add `%k` to the squeue command to see the `--comments` section
```console
squeue -u $(whoami) -o "%.14i %.8u %.20k %.20j"
```

Hope this helps!
