### ISSUE TITLE
Shell comand within if-else statement do not print when use "--print-compilation" arguemnt

### ISSUE THREAD

**Issue by y9c** [snakemake/snakemake#2798]
Example input:

```yaml

rule test:
  input: a.txt
  output: b.txt
  run:
    if 1 > 0:
      shell("echo 1")
    else:
      shell("echo 0")
```

run snakemake command with `-p` command do not show these command in the shell.
