### ISSUE TITLE
Snakemake 8.9.0 on a singularity slurm cluster combination error

### ISSUE THREAD

**Issue by tinu-t** [snakemake/snakemake#2808]
I am trying to run snakemake 8.9.0 using singularity on a slurm cluster,
Constantly getting this error, not sure what is wrong with the syntax

**Command**:
```
snakemake --cores 3 --configfile config.yaml --executor cluster-generic --cluster-generic-submit-cmd 'sbatch -t {params.res_time} --cpus-per-task {threads} --mem-per-cpu {params.res_mem} -o {params.lsf_log}' -j 20 -k -p --notemp --latency-wait 24 --rerun-incomplete --use-singularity --singularity-args '--bind /cluster/snakemake
-path'
```

**Error:**
`__main__.py: error: argument --apptainer-args/--singularity-args: expected one argument
`

**Comment by tinu-t** [comment]
The apptainer parameters had to be written in a YAML file and given as argument to the `-profile` argument like shown below:

```snakemake --cores 3 --configfile config.yaml --executor cluster-generic --cluster-generic-submit-cmd 'sbatch -t {params.res_time} --cpus-per-task {threads} --mem-per-cpu {params.res_mem} -o {params.lsf_log}' -j 20 -k -p --notemp --latency-wait 24 --rerun-incomplete --profile ./profile/apptainer```

**cat ./profile/apptainer**
```
use-singularity: True
singularity-args: "\"--bind /cluster/snakemake/\""
```

**Comment by amadeovezz** [comment]
I am also running into this error while trying to use `singularity-args` with `slurm`:

`__main__.py: error: argument --apptainer-args/--singularity-args: expected one argument `

 The above solution did not work and I've also tried passing it through the command line:
 `--use-singularity --singularity-args "--bind /some/path"`

I'm not sure if it is an issue with the `snakemake-executor-plugin-slurm` or with snakemake itself. I noticed this regression after I upgraded from 8.4.2.

## Additional details:

### Config

```
executor: slurm

# Slurm specific
default-resources:
  slurm_account: "some_account"
  slurm_partition: "some_partition,common"
  runtime: 60 
  mem_mb: 4000
  nodes: 1
 # Non-standard resource specifications
  slurm_extra: "'--exclude=some_node'"

jobs: 1 
printshellcmds: True
restart-times: 0 

use-singularity: True
singularity-args: "--bind some/path"
```
### Minimal snakefile

```
rule all:
    output:
        "test_output.txt"
    singularity:
        "/path/to/v4/RSingleCell.sif" 
    shell:
        "ls /mnt > {output}"
 ```

### Command

`snakemake  --profile ./profiles/generic/`

### My current versions:

```
snakemake-executor-plugin-slurm 0.4.4             
snakemake-executor-plugin-slurm-jobstep 0.2.1              
snakemake-interface-common 1.17.2             
snakemake-interface-executor-plugins 9.1.1             
snakemake-interface-report-plugins 1.0.0             
snakemake-interface-storage-plugins 3.2.0             
```

Any help is appreciated 🙏
