### ISSUE TITLE
Add possibility to provide empty default resources in a profles (as was possible with SnakeMake 7.x.x)

### ISSUE THREAD

**Issue by sven0schuierer** [snakemake/snakemake#2820]
**Is your feature request related to a problem? Please describe.**
See the setup for me bug report "Using option --drmaa_logs crashes snakemake #2819" except the profile config looks now as follows:

```
jobs: 100
latency-wait: 120

default-resources:
    mem_mb:    1000
    h_vmem_mb: 1200
    h_rt:  14400
    additional_drmaa_options: ''
    
executor: drmaa
drmaa-args: "-V -l h_rt={resources.h_rt} -l m_mem_free={resources.mem_mb}M -l h_vmem={resources.h_vmem_mb}M -pe smp {threads} {resources.additional_drmaa_options}"
drmaa-log-dir: drmaa_logs
```

If I run SnakeMake as in the bug report, I get:
```
(snakemake-tutorial-v8+) $ snakemake --cores 1 --use-conda --profile drmaa
Using profile drmaa for setting default command line arguments.
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Using shell: /usr/bin/bash
Provided remote nodes: 100
Job stats:
job          count
---------  -------
map_reads        1
total            1

Select jobs to execute...
InputFunctionException in rule map_reads in file <path to snakemake-tutorial>/snakemake-tutorial-v8+/snakemake-snakemake-tutorial-data-be6ae5a/Snakefile, line 1:
Error:
  WorkflowError:
    Failed to evaluate resources value ''.
        String arguments may need additional quoting. E.g.: --default-resources "tmpdir='/home/user/tmp'" or --set-resources "somerule:someresource='--nice=100'". This also holds for setting resources inside of a profile, where you might have to enclose them in single and double quotes, i.e. someresource: "'--nice=100'".
    SyntaxError: invalid syntax (<string>, line 0)
Wildcards:

Traceback:
 (rule map_reads, line 1, <path to snakemake-tutorial>/snakemake-tutorial-v8+/snakemake-snakemake-tutorial-data-be6ae5a/Snakefile)
(snakemake-tutorial-v8+)
```

**Describe the solution you'd like**
I would like SnakeMake to accept empty default resources

**Describe alternatives you've considered**
Provide an option that I would specify directly in  "drmaa_option", e.g. -V as an additional_drmaa_options
