### ISSUE TITLE
mem_mb parsing error in workflow profile

### ISSUE THREAD

**Issue by zhujack8** [snakemake/snakemake#2903]
**Snakemake version**
7.32.4

**Describe the bug**
max(2 * input.size_mb, 1024*4) can be used to configure mem_mb in "default-resources" of the workflow profile, but it has parsing error when it is copied to"set-resources" in the workflow profile to configure mem_mb for a rule.

**Logs**
myrule: Could not parse mem_mb=max(2 * input.size_mb, 1024*10)
Error submitting jobscript (exit code 1):

**Minimal example**
`
default-resources:
    threads: 2
    runtime: 30
    mem_mb: max(2 * input.size_mb, 1024*4)
    disk_mb: 1024*4

set-resources:
    myrule:
        mem_mb: max(2 * input.size_mb, 1024*10)

`
**Additional context**
Can a function be used in the workflow profile to configure mem_mb for a rule?

`
set-resources:
    myrule:
        mem_mb: get_mem_mb(base_mem_gb=4)
`

**Comment by pdimens** [comment]
Are you indenting the yaml file? It should look like:
```yaml
default-resources:
  threads: 2
  runtime: 30
  mem_mb: max(2 * input.size_mb, 10244)
  disk_mb: 10244

set-resources:
  myrule:
    mem_mb: max(2 * input.size_mb, 1024*10)
```
