### ISSUE TITLE
slurm executor not printing logs on fail

### ISSUE THREAD

**Issue by pdimens** [snakemake/snakemake#2911]
**Snakemake version**
8.13

**Describe the bug**
I'm using the `slurm` executor plugin to have Snakemake submit jobs to cluster on my behalf. In addition to this, I'm also using the `fs` plugin to handle copying and retrieving files from the high-speed scratch directory we are guided to use on our HPC. The profile looks like this:
```yaml
__use_yte__: true
executor: slurm
default-resources:
  slurm_account: xxxxxx
  slurm_partition: regular
  mem_mb: attempt * 2000
  runtime: 10
jobs: 4
latency-wait: 60
retries: 1
default-storage-provider: fs
local-storage-prefix: /home2/xxxxxx
shared-fs-usage:
  - persistence
  - software-deployment
  - sources
  - source-cache
```

And submitting to the cluster on the login node:
```bash
snakemake --snakefile workflow.smk --cores 10 --workflow-profile profile/
```

The workflow will create the DAG and copy files as expected, however the jobs tend to fail with STDERR logs like (account name anonymized):
```
Error in rule genome_faidx:
    message: SLURM-job '1607095' failed, SLURM status is: 'FAILED'. For further error details see the cluster/cloud log and the log files of the involved rule(s).
    jobid: 10
    input: Genome/genome.fasta.gz (retrieve from storage)
    output: Genome/genome.fasta.gz.fai (send to storage), Genome/genome.fasta.gz.gzi (send to storage)
    log: Genome/genome.fasta.gz.faidx.log (send to storage), /fs/XXXXXX/workdir/XXXXX/harpy/.snakemake/slurm_logs/rule_genome_faidx/1607095.log (check log file(s) for error details)
    shell:
        
        if [ "True" = "True" ]; then
            samtools faidx --gzi-idx /home2/XXXXX/fs/Genome/genome.fasta.gz.gzi --fai-idx /home2/XXXXXX/fs/Genome/genome.fasta.gz.fai /home2/XXXXX/fs/Genome/genome.fasta.gz 2> /home2/XXXXX/fs/Genome/genome.fasta.gz.faidx.log
        else
            samtools faidx --fai-idx /home2/XXXXX/fs/Genome/genome.fasta.gz.fai /home2/XXXXX/fs/Genome/genome.fasta.gz 2> /home2/XXXXX/fs/Genome/genome.fasta.gz.faidx.log
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    external_jobid: 1607095
```

However, the SLURM log that would reveal troubleshooting information, `.snakemake/slurm_logs/rule_genome_faidx/1607095.log` is **not present** and only gets written after **successful** completion of a job.  This has been consistent for several workflows and different rules.

**Comment by cmeesters** [comment]
I am unable to reproduce this error. Can you check the node status in case of failing jobs, please? `sacct -o nodelist,state` will indicate one or more nodes of failed jobs. `scontrol show node <some node of a failed job> | grep State` gives the state.

**Comment by pdimens** [comment]
Here's another such log:
```bash
Error in rule qc_fastp:
    message: SLURM-job '1618942' failed, SLURM status is: 'FAILED'. For further error details see the cluster/cloud log and the log files of the involved rule(s).
    jobid: 1
    input: /fs/cbsunt246/workdir/pdimens/harpy/test/fastq/sample1.F.fq.gz (retrieve from storage), /fs/cbsunt246/workdir/pdimens/harpy/test/fastq/sample1.R.fq.gz (retrieve from storage)
    output: QC/sample1.R1.fq.gz (send to storage), QC/sample1.R2.fq.gz (send to storage), QC/reports/data/fastp/sample1.fastp.json (send to storage)
    log: QC/reports/sample1.html (send to storage), QC/logs/fastp/sample1.log (send to storage), /fs/cbsunt246/workdir/pdimens/harpy/.snakemake/slurm_logs/rule_qc_fastp/sample1/1618942.log (check log file(s) for error details)
    conda-env: /fs/cbsunt246/workdir/pdimens/harpy/.snakemake/conda/3868729ed4cdf57e23c7b2c2632ebf5c_
    shell:
        
        fastp --trim_poly_g --cut_right --length_required 30 --max_len1 150 --detect_adapter_for_pe  --thread 4 -i /home2/pd348/fs/fs/cbsunt246/workdir/pdimens/harpy/test/fastq/sample1.F.fq.gz -I /home2/pd348/fs/fs/cbsunt246/workdir/pdimens/harpy/test/fastq/sample1.R.fq.gz -o /home2/pd348/fs/QC/sample1.R1.fq.gz -O /home2/pd348/fs/QC/sample1.R2.fq.gz -h /home2/pd348/fs/QC/reports/sample1.html -j /home2/pd348/fs/QC/reports/data/fastp/sample1.fastp.json -R "sample1 QC Report" 2> /home2/pd348/fs/QC/logs/fastp/sample1.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    external_jobid: 1618942

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-06-13T152236.344429.snakemake.log
WorkflowError:
At least one job did not complete successfully.

> tree .snakemake/slurm_logs/
.snakemake/slurm_logs/
└── rule_qc_fastp
    ├── sample1
    └── sample2

```
Meanwhile, the configured NAS directory from the SLURM profile has this structure and the files never copied over:
```
> tree /home2/pd348                                                                                                                                                          24-06-13 @ 15:23
/home2/pd348
└── fs
```

**Comment by cmeesters** [comment]
My idea was that failing nodes will not be able to feed back log information. Now, by NAS you mean NFS? Regardless, it should be written - eventually. What puzzles me is the distinction between failed and completed jobs: If such an error occurs, it is most likely a cluster error, which occurs always.

Can you confirm (with a minimal example, which always fails), that without the fs-plugin (you can just out comment the respective lines in your profile), the joblog is written?

**Comment by pdimens** [comment]
Sure, I can try that. Just to be clear, the config will look like this?
```yaml
executor: slurm
default-resources:
  slurm_account: nt246_0001
  slurm_partition: short
  mem_mb: attempt * 2000
  runtime: 10
jobs: 4
latency-wait: 60
retries: 0
#default-storage-provider: fs
#remote-job-local-storage-prefix: /home2/pd348
#local-storage-prefix: /home2/pd348
#shared-fs-usage:
#  - persistence
#  - software-deployment
#  - sources
#  - source-cache
```
