### ISSUE TITLE
Support standard Python virtual env. for rules

### ISSUE THREAD

**Issue by ccoulombe** [snakemake/snakemake#3124]
**Is your feature request related to a problem? Please describe.**
Using conda environment is not always possible nor a good option, for instance in super computer center where conda is prohibited or non-functionnal. Yet all softwares and python packages are readily available (outside of a conda env.).

**Describe the solution you'd like**
Allow snakemake to use or create a standard python virtual env. in a Slurm job.

Having support for requirements file in the `env` entry, eg :
```
    env:
        "envs/cutadapt-requirements.txt"
    envmodules:
        "python/3.12"      
```
or listing the wheels to be installed by pip:
```
    requirements:
        "cutadapt==4.9"
    envmodules:
        "python/3.12"      
```

When this rule is executed, it would create a virtual env. using `python -m venv` in `$SLURM_TMPDIR` or any user configured directory, using python 3.12 module (lmod) and install the requirements file `envs/cutadapt-requirements.txt` or install the listed packages (`cutadapt==4.9`).
Or activate an existing virtual env. if it exists.

**Describe alternatives you've considered**
- Avoiding snakemake usage and rely on bash scripts
- Use the shell entry to create and source a virtual env.
- Use a shell script via the script entry to bundle venv creation and execution
- Use a tool wrapper to create the virtual env., activate it, run the tool.

**Additional context**
Snakemake is used in numerous context and used to submit jobs on clusters with slurm. It would be nice if it could simply reuse tools that are readily available inside each allocated job.

**Comment by nagocht** [comment]
This would be sooo amazing.

**Comment by mmcdermott** [comment]
may be related: https://github.com/snakemake/snakemake/issues/566

**Comment by mmcdermott** [comment]
I am just getting started with Snakemake in a setting where I plan to have users submit `requirements.txt` files for various jobs or stages that I'd like to use for environment management, so this would be appealing. In my setting, `conda` can theoretically be available, it just may not be the best solution to have individual stages document their dependencies with an `env.yml` file vs. a `pip` `requirements.txt` file. To that end, I had thought to create a snakemake wrapper that just creates a `conda` `env.yml` file to match a given `pip` `requirements.txt` file, and this could be pretty naively extended to support a more generic `venv` specification. That wouldn't be helpful in the case that `conda` itself is not installed on the machine, but it would be helpful in the case that you are comfortable using `conda` to encapsulate your environment even if you'd rather not use it for dependency management or package installation or its other features. Would such a wrapper be helpful for you, @ccoulombe? If so, I can tag it here if I end up making it.

**Comment by ccoulombe** [comment]
> may be related: #566

This is different, that user is asking for documented : `pip install snakemake` (in its own virtualenv) to use snakemake, rather than here it is to use virtual env inside rules.

If I understand correctly your second message, this would still require conda to be available? and in my case, this is not possible as conda lead to a plethora of issues.

**Comment by adamtupper** [comment]
Support for this would be great! As it currently stands, I'm hesitant to adopt Snakemake because of this conda dependency.

**Comment by YuanfengZhang** [comment]
I think it's more practicable for snakemake to introduce 3rd-party env management tool than parsing requirements. There is really no need rebuilding the wheels.
[Pixi](https://github.com/prefix-dev/pixi) seems to fit well.
1. It can create and manage multiple envs according to a single pixi.toml file.
2. Packages from conda channels and Pypi are available.

It does have the potential to replace conda in snakemake. For example:
Before:
```bash
├── Snakefile  # the main snakefile
├── rules
│   ├── tool_a
│   │   ├── conda.yaml
│   │   └── tool_a.smk
│   ├── tool_b
│   │   ├── conda.yaml
│   │   └── tool_b.smk
```

in rules/tool_a/tool_a.smk:
```snakemake
input:
    ...
output:
    ...
conda:
    "conda.yaml"
shell:
    """
    do something with tool_a
    """
```

in rules/tool_a/conda.yaml:
```yaml
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::tool_a>=1.0
  - pip
  - pip:
    - tool_c
    - git+https://some_url@develop
```
and the cmdln would be `snakemake --cores 8 --use-conda`

After:
```bash
├── Snakefile
├── pixi.toml  # single file handling all envs
├── rules
│   ├── tool_a
│   │   └── tool_a.smk
│   ├── tool_b
│   │   └── tool_b.smk
```

in rules/tool_a/tool_a.smk:
```snakemake
input:
    ...
output:
    ...
env:
    "tool_a"
shell:
    """
    do something with tool_a
    """
```

in pixi.toml (a more real example):
```toml
[workspace]
name = "snakemake"
platforms = ["linux-64"]
channels = ["conda-forge", "default", "bioconda"]

[dependencies]
python = "3.12.*"
snakemake = "~=9.3.0"

[feature.preprocess]
channels = ["conda-forge", "bioconda"]

[feature.preprocess.dependencies]
fastp = "~=0.24.1"
fastqc = "~=0.11.8"
openjdk = ">=17.0.0"

[feature.align]
channels = ["conda-forge", "bioconda"]

[feature.align.dependencies]
bwa-meme = "~=1.0.6"

[feature.modeling]
channels = ["conda-forge"]

[feature.modeling.dependencies]
scikit-learn = "1.6.*"
shap = ">=0.47.2"

[feature.modeling.pypi-dependencies]
polars = {version = "~=1.27.1", extras = ["pandas", "numpy", "pyarrow", "excel"]}
supervised = {git = "https://github.com/mljar/mljar-supervised"}

[environments]
pre = {features = ["preprocess"], no-default-feature = true}
align = {features = ["align"], no-default-feature = true}
model = {features = ["modeling"], no-default-feature = true}
```
and snakemake can run `pixi shell -e {the_env_name_specified_in_env_field}` before running the shell field or run field.

Until now, it's not recommended to include pixi in the shell field ourselves, because the activation is not clean and may cause issues.

One more thing, direnv is not a good choice, I guess. In shell field users should be allowed to change dictionary. However, if the shell field is always parsed and saved as a temporaru .sh file then it is good to go.

**Comment by YuanfengZhang** [comment]
And it's obvious that pixi should not be used together with conda. As a result, there should at least several flags for snakemake on terminal:
`--use-pixi`,  no mutual exclusion with conda, but snakemake should raise error if both `--use-pixi` and `--use-conda` are specificed while there is some rules containing both `env` and `conda` fields.
`--pixi-create-envs-only`
`--pixi-cleanup-envs`
and other equivalent flags.

**Comment by YuanfengZhang** [comment]
The package cache, config files, envs of pixi can and should all be stored in the snakemake project dir. It won't contaminate anything outside. pixi is a single binary file, making it very convenient to deploy snakemake projects on slurm and other job system.

**Comment by YuanfengZhang** [comment]
Any other thoughs, guys? :)

**Comment by YuanfengZhang** [comment]
And, if we want to just use tools from two existing envs, luckily pixi has a feature help combining envs:
```toml
[environments]
pre = {features = ["preprocess"], no-default-feature = true, solve-group = "fq2bam"}
align = {features = ["align"], no-default-feature = true}
fq2bam = {features = ["preprocess", "align"], solve-group = "fq2bam"}
```

Of course it's statically written in pixi.toml but we can make snakemake able to add envs at runtime:
```
rule fq2bam：
    input:
        ...
    output:
        ...
    env:
        {name: "fq2bam", envs: ["preprocess", "align"]}
    shell:
        ...
```
Just require snakemake to look up all env fields in included rules, and try to solve them together with the static pixi.toml, generating another pixi.toml named "snakemake.toml" and then prepare the envs.

see [Manifest](https://pixi.sh/latest/reference/pixi_manifest/)
