### ISSUE TITLE
Per rule based "apptainer-args"

### ISSUE THREAD

**Issue by grabear** [snakemake/snakemake#3478]
From what I can tell in the docs:  https://snakemake.readthedocs.io/en/stable/executing/cli.html#snakemake.cli-get_argument_parser-apptainer/singularity

You can only set the "global" `--apptainer-args`.  Is there a way to set, "per-rule" `--apptainer-args`?  

It would be useful to do this in profile config:
```yaml
set-apptainer-args:
    my_good_boy_rule:
        - '--cleanenv'
        - '--workdir path'
```
the command line:
```bash
--set-apptainer-args my_good_boy_rule:"--cleanenv --workdir path"
```
and as a rule's directive:
```python
rule my_good_boy_rule:
    input: who cares
    output: who cares
    container: good_boy.sif
    container_args: "--cleanenv --workdir path"
```
