### ISSUE TITLE
Incorrect omission of post-deploy scripts when using gitlab source provider for a module

### ISSUE THREAD

**Issue by LukaP-BB** [snakemake/snakemake#3615]
**Snakemake version**
9.5.1

**Describe the bug**
When using the gitlab function to load a module as below, snakemake gives the following warning : 
`Conda environment file https://gitlab.com/api/v4/projects/[REDACTED] &private_token=[REDACTED] does not end on .yaml or .yml. Omitting search for pin file (https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#freezing-environments-to-exactly-pinned-packages).`

```yaml
module main_smk:
    snakefile: gitlab("user/repo", path="workflow/Snakefile", branch="master")
    config: config
```

Cloning the repo and pointing to the local snakefile raises no warning.

If any additional information is needed, feel free to ask and I'll do as best as I can to provide.
