### ISSUE TITLE
Config file cluster.json not found when using --profile

### ISSUE THREAD

**Issue by mivade** [snakemake/snakemake#422]
**Snakemake version**
5.18.1

**Describe the bug**
I have a Snakemake profile located in a directory named `profile` which looks like this:

```yaml
restart-times: 3
latency-wait: 60
rerun-incomplete: true
cores: 64
local-cores: 8
verbose: true
cluster-config: "cluster.json"
jobname: {name}.{rule}.{jobid}.sh
drmaa: |
    request_cpus = {threads}
    request_memory = {cluster.memory}
    getenv = true
    error = logs/cluster/{rule}.$(ClusterId)_$(Process).err
    output = logs/cluster/{rule}.$(ClusterId)_$(Process).out
    requirements = {cluster.requirements}
```

Alongside that file in the `profile` directory there is a `cluster.json` file. If I use the command `snakemake --profile=$PWD/profile ...` I get the following error:

```
snakemake.exceptions.WorkflowError: Config file cluster.json not found.
```

If I instead edit the `cluster-config` setting to use an absolute path everything works as expected. Ideally Snakemake should interpret relative paths in a profile configuration file to be relative to the containing directory.
