### ISSUE TITLE
Intermittent behaviour on wildcards in output section.

### ISSUE THREAD

**Issue by jhidding** [snakemake/snakemake#951]
**Snakemake version**
Snakemake 6.1.1 on Python 3.9 on Fedora 33, also tried versions 6.0 and 5.32, 5.10 (random older versions) the same applies.

**Describe the bug**
Running snakemake on a Snakefile that contains wildcards in the output specification. Example:

```yaml
rule all:
        input:
                "output.txt"

rule combine:
        input:
                expand("x{n}.txt", n=range(10))
        output:
                "output.txt"
        shell:
                "cat {input} > {output}"

rule generate:
        output:
                "x{n}.txt"
        shell:
                "echo \"{wildcards.n}\" > x{wildcards.n}.txt"
```

About 90% of the time, this Snakefile results in the following output:

```
Building DAG of jobs...
MissingInputException in line 5 of /mnt/Data/Code/academy/parallel-python-workshop/trigger_bug/Snakefile:
Missing input files for rule combine:
x6.txt
x0.txt
x9.txt
x2.txt
x5.txt
x4.txt
x8.txt
x3.txt
x7.txt
x1.txt
```

Trying a few times eventually results in success (a `output.txt` containing the numbers 0-9).

The same behaviour is found at dry runs (`-n`) or creating a dag (`--dag`).
