### ISSUE TITLE
AmbiguousRuleException whereas only one input file exists

### ISSUE THREAD

**Issue by tbigot** [snakemake/snakemake#970]
**Snakemake version**
6.2.1

**Describe the bug**
Snakemake complains about ambiguous rules, but only one file really exists.

**Logs**

```
Building DAG of jobs...
AmbiguousRuleException:
Rules copy and unlzma are ambiguous for the file step/raw_reads/PE_1.fastq.
Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
Wildcards:
        copy: dataset=PE_1
        unlzma: dataset=PE_1
Expected input files:
        copy: /pasteur/zeus/projets/p02/stella-run/projects/sars-cov-2-detection/positives/PE_1.fastq
        unlzma: /pasteur/zeus/projets/p02/stella-run/projects/sars-cov-2-detection/positives/PE_1.fastq.xzExpected output files:
        copy: step/raw_reads/PE_1.fastq
        unlzma: step/raw_reads/PE_1.fastq
```
(there is a missing `\n` before `Expected output files`)

```sh
$ ls /pasteur/zeus/projets/p02/stella-run/projects/sars-cov-2-detection/positives/PE_1.fastq
/pasteur/zeus/projets/p02/stella-run/projects/sars-cov-2-detection/positives/PE_1.fastq
$ ls /pasteur/zeus/projets/p02/stella-run/projects/sars-cov-2-detection/positives/PE_1.fastq.xz
ls: cannot access '/pasteur/zeus/projets/p02/stella-run/projects/sars-cov-2-detection/positives/PE_1.fastq.xz': No such file or directory
```

**Minimal example**

```python
rule unlzma:
    input:
        config["sample"]["path"]+"/{dataset}.fastq.xz"
    output:
        "step/raw_reads/{dataset}.fastq"
    resources: cpus=1
    shell:
        "xz -d -c '{input}' > '{output}'" 

rule copy:
    input:
        config["sample"]["path"]+"/{dataset}.fastq"
    output:
        "step/raw_reads/{dataset}.fastq"
    resources: cpus=1
    shell:
        "cp '{input}' '{output}'"

```
